const TIMEZONE = 'America/Chicago';
const CALLBACK_WINDOW_SECONDS = 600;
const BUSINESS_HOURS_START = 7;
const BUSINESS_HOURS_END = 17;
const AIRCALL_API_RATE_LIMIT_MS = 500;

module.exports = {
    TIMEZONE,
    CALLBACK_WINDOW_SECONDS,
    BUSINESS_HOURS_START,
    BUSINESS_HOURS_END,
    AIRCALL_API_RATE_LIMIT_MS
};
